# Generated by Django 5.2.15 on 2026-07-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('text', 'Pasted text'), ('website', 'Website'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'Plain text file')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('num_chunks', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding_vector_id', models.CharField(max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
