# Generated by Django 5.2.15 on 2026-07-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ai_visibility_score', models.PositiveIntegerField(default=0)),
                ('geo_score', models.PositiveIntegerField(default=0)),
                ('aeo_score', models.PositiveIntegerField(default=0)),
                ('seo_score', models.PositiveIntegerField(default=0)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('citation_score', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
