"""llms.txt generation — the emerging convention AI crawlers read to understand
a site (https://llmstxt.org). Built ONLY from the org's real data: profile,
valid generated FAQ schema and Knowledge Base content. No invention.
"""
from __future__ import annotations

from apps.ai_optimization.generators import build_org_profile
from apps.ai_optimization.models import SchemaMarkup
from apps.organizations.models import Domain


def build_llms_txt(organization) -> str:
    profile = build_org_profile(organization)
    lines: list[str] = [f"# {organization.name}", ""]

    if profile.get("description"):
        lines += [f"> {profile['description']}", ""]
    if organization.industry:
        lines += [f"Industry: {organization.industry}", ""]

    domains = list(Domain.objects.filter(organization=organization))
    if domains:
        lines.append("## Links")
        lines.append("")
        for d in domains:
            label = "Website (primary)" if d.is_primary else "Website"
            lines.append(f"- [{label}]({d.url})")
        lines.append("")

    faq = (
        SchemaMarkup.objects.filter(
            organization=organization,
            schema_type=SchemaMarkup.SchemaType.FAQ,
            status=SchemaMarkup.Status.DONE,
            is_valid=True,
        )
        .order_by("-created_at")
        .first()
    )
    if faq:
        entries = faq.json_ld.get("mainEntity", [])
        if entries:
            lines.append("## FAQ")
            lines.append("")
            for item in entries:
                q = item.get("name", "").strip()
                a = item.get("acceptedAnswer", {}).get("text", "").strip()
                if q and a:
                    lines.append(f"- **{q}** {a}")
            lines.append("")

    lines.append(
        "_This file follows the llms.txt convention and is generated by AEO.GEO "
        "from the organization's own published content._"
    )
    return "\n".join(lines) + "\n"
