"""Public, AI-crawlable delivery surface.

This is the "actually reach the AI" half of AEO: an opt-in profile page at
/p/<slug>/ carrying the org's generated JSON-LD + FAQ as server-rendered HTML,
and /p/<slug>/llms.txt for AI crawlers that look for it. Everything shown is
generated from the org's own content — the same artifacts the product builds.
"""
import json

from django.http import Http404, HttpResponse
from django.utils.html import escape

from apps.ai_optimization.llms_txt import build_llms_txt
from apps.ai_optimization.models import SchemaMarkup
from apps.organizations.models import Domain, Organization


def _get_public_org(slug: str) -> Organization:
    org = Organization.objects.filter(slug=slug, public_profile=True).first()
    if org is None:
        raise Http404
    return org


def public_llms_txt(request, slug: str):
    org = _get_public_org(slug)
    return HttpResponse(build_llms_txt(org), content_type="text/plain; charset=utf-8")


def public_profile(request, slug: str):
    org = _get_public_org(slug)

    markups = SchemaMarkup.objects.filter(
        organization=org, status=SchemaMarkup.Status.DONE, is_valid=True
    ).order_by("schema_type", "-created_at")
    # newest per type only — never two conflicting blocks of the same @type
    seen: set[str] = set()
    schemas = []
    for m in markups:
        if m.schema_type not in seen:
            seen.add(m.schema_type)
            schemas.append(m.json_ld)

    faq = next((s for s in schemas if s.get("@type") == "FAQPage"), None)
    org_schema = next((s for s in schemas if s.get("@type") == "Organization"), None)
    description = (org_schema or {}).get("description", "") or org.industry
    primary = (
        Domain.objects.filter(organization=org, is_primary=True).first()
        or Domain.objects.filter(organization=org).first()
    )

    name = escape(org.name)
    json_ld_blocks = "\n".join(
        f'<script type="application/ld+json">{json.dumps(s, ensure_ascii=False)}</script>'
        for s in schemas
    )
    faq_html = ""
    if faq:
        items = "".join(
            f"<details><summary>{escape(q.get('name', ''))}</summary>"
            f"<p>{escape(q.get('acceptedAnswer', {}).get('text', ''))}</p></details>"
            for q in faq.get("mainEntity", [])
        )
        faq_html = f"<h2>Frequently asked questions</h2>{items}"

    website_html = (
        f'<p><a href="{escape(primary.url)}" rel="me">{escape(primary.url)}</a></p>'
        if primary
        else ""
    )

    html = f"""<!doctype html>
<html lang="{escape(org.primary_language or 'en')}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{name} — company profile</title>
<meta name="description" content="{escape(description[:300])}">
<link rel="alternate" type="text/plain" href="/p/{escape(org.slug)}/llms.txt" title="llms.txt">
{json_ld_blocks}
<style>
  body{{font-family:system-ui,sans-serif;max-width:44rem;margin:0 auto;padding:2.5rem 1.25rem;line-height:1.6;color:#111827}}
  h1{{letter-spacing:-.02em}} details{{border:1px solid #e5e7eb;border-radius:.6rem;padding:.6rem .9rem;margin:.5rem 0}}
  summary{{font-weight:600;cursor:pointer}} footer{{margin-top:3rem;font-size:.8rem;color:#6b7280}}
</style>
</head>
<body>
<main>
  <h1>{name}</h1>
  {f"<p>{escape(description)}</p>" if description else ""}
  {website_html}
  {faq_html}
</main>
<footer>Structured, AI-readable profile · generated by AEO.GEO from {name}'s own content ·
<a href="/p/{escape(org.slug)}/llms.txt">llms.txt</a></footer>
</body>
</html>"""
    return HttpResponse(html)
