# Generated by Django 5.2.15 on 2026-07-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_type', models.CharField(choices=[('faq', 'FAQ Page'), ('organization', 'Organization'), ('product', 'Product'), ('breadcrumb', 'Breadcrumb')], max_length=20)),
                ('json_ld', models.JSONField(blank=True, default=dict)),
                ('applied_to_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_markups', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
