# Generated by Django 5.2.15 on 2026-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
